### PR TITLE
How to integrate your web app with the national bank of malawi payment gateway

### PR DESCRIPTION
**Pull request by mozesi**
Linking your system with the NB payment API.

### CODE REVIEW

**Review by zikani03 — CHANGES_REQUESTED** [review]
@mozesi  This is looking good.

A few comments, 
1. I know we briefly chatted about the format not being there, but maybe add the following below the title for now

```
Date: YYYY-MM-DD
Author: <Your Name>
```

2. maybe could add a couple of screenshots ?

3. Maybe we can add a section or links at the bottom for where to start to get access to the API, maybe a link to NBM website

**Comment by mozesi** [comment]
> @mozesi This is looking good.
> 
> A few comments,
> 
>     1. I know we briefly chatted about the format not being there, but maybe add the following below the title for now
> 
> 
> ```
> Date: YYYY-MM-DD
> Author: <Your Name>
> ```
> 
>     2. maybe could add a couple of screenshots ?
> 
>     3. Maybe we can add a section or links at the bottom for where to start to get access to the API, maybe a link to NBM website

**Comment by mozesi** [comment]
@zikani03  Screenshots will need an interaction with the API's test environment. Something that requires a formal registration with NB.

**Comment by zikani03** [comment]
@mozesi Alright, this is fine as it is - we can update it later. Like I said, am keen to get this merged so we have some content.

Are you okay with us merging this in ?

**Comment by mozesi** [comment]
@zikani03 I have done presumably some final reviews for now.  You can merg.

**Pull request merged**
